import { rc } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const X = localFont({
  src: "../public/X-Regular.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={rc(
          X.className,
          "selection:text-gray-600 selection:bg-teal-200"
        )}
      >
        {children}
      </body>
    </html>
  );
}
